const categories = [
  { id: 'all', name: '全部' },
  { id: 'hot', name: '热菜' },
  { id: 'staple', name: '主食' },
  { id: 'soup', name: '汤粥' },
  { id: 'sweet', name: '小甜口' },
];

const dishes = [
  {
    id: 'braised-ribs',
    name: '红烧排骨',
    category: 'hot',
    categoryName: '热菜',
    desc: '小火慢炖，软糯入味',
    tag: '爷爷拿手',
    color: '#f2c1a6',
    recommended: true,
  },
  {
    id: 'tomato-egg',
    name: '番茄炒蛋',
    category: 'hot',
    categoryName: '热菜',
    desc: '酸甜开胃，百吃不厌',
    tag: '家常味',
    color: '#f8b48a',
  },
  {
    id: 'braised-pork',
    name: '红烧肉',
    category: 'hot',
    categoryName: '热菜',
    desc: '肥而不腻，入口即化',
    tag: '暖心',
    color: '#e89070',
  },
  {
    id: 'yuxiang-pork',
    name: '鱼香肉丝',
    category: 'hot',
    categoryName: '热菜',
    desc: '酸辣咸香，开胃下饭',
    tag: '开胃',
    color: '#f5a66f',
  },
  {
    id: 'mapo-tofu',
    name: '麻婆豆腐',
    category: 'hot',
    categoryName: '热菜',
    desc: '麻辣鲜香，嫩滑可口',
    tag: '下饭',
    color: '#e87c5a',
  },
  {
    id: 'garlic-greens',
    name: '蒜蓉炒青菜',
    category: 'hot',
    categoryName: '热菜',
    desc: '清爽脆嫩，简单好味',
    tag: '清爽',
    color: '#a8d8a0',
  },
  {
    id: 'steamed-egg',
    name: '蒸水蛋',
    category: 'hot',
    categoryName: '热菜',
    desc: '嫩滑如豆腐，老少皆宜',
    tag: '软乎乎',
    color: '#f8d78a',
  },
  {
    id: 'potato-shreds',
    name: '清炒土豆丝',
    category: 'hot',
    categoryName: '热菜',
    desc: '脆爽爽，越嚼越香',
    tag: '家常味',
    color: '#f5c842',
  },
  {
    id: 'egg-fried-rice',
    name: '蛋炒饭',
    category: 'staple',
    categoryName: '主食',
    desc: '粒粒分明，香气扑鼻',
    tag: '快手',
    color: '#f8d78a',
  },
  {
    id: 'tomato-noodles',
    name: '番茄鸡蛋面',
    category: 'staple',
    categoryName: '主食',
    desc: '汤浓面滑，酸甜暖胃',
    tag: '暖胃',
    color: '#f5a66f',
  },
  {
    id: 'congee',
    name: '白米粥',
    category: 'staple',
    categoryName: '主食',
    desc: '绵软香甜，养胃润心',
    tag: '养胃',
    color: '#f0e8c8',
  },
  {
    id: 'lean-pork-congee',
    name: '皮蛋瘦肉粥',
    category: 'soup',
    categoryName: '汤粥',
    desc: '咸香滑软，越喝越暖',
    tag: '暖胃',
    color: '#c8dfb0',
  },
  {
    id: 'tomato-egg-soup',
    name: '番茄蛋花汤',
    category: 'soup',
    categoryName: '汤粥',
    desc: '酸甜鲜美，清爽解腻',
    tag: '清爽',
    color: '#f8b48a',
  },
  {
    id: 'winter-melon-soup',
    name: '冬瓜排骨汤',
    category: 'soup',
    categoryName: '汤粥',
    desc: '清甜鲜美，滋补润燥',
    tag: '滋补',
    color: '#b5d4a0',
  },
  {
    id: 'red-bean-soup',
    name: '红豆薏米汤',
    category: 'sweet',
    categoryName: '小甜口',
    desc: '软糯香甜，健脾祛湿',
    tag: '健康',
    color: '#f3b7b2',
  },
  {
    id: 'tangyuan',
    name: '汤圆',
    category: 'sweet',
    categoryName: '小甜口',
    desc: '软糯香甜，一口幸福',
    tag: '团圆',
    color: '#f0c8d8',
  },
];

const familyMembers = ['我', '奶奶', '爸爸', '妈妈', '孩子'];

const tasteOptions = ['照常', '清淡', '少辣', '多葱', '不要香菜'];

module.exports = {
  categories,
  dishes,
  familyMembers,
  tasteOptions,
};
